### ISSUE TITLE
Installing P4J using python3.11

### ISSUE THREAD

**Issue by fcotizelati** [phuijse/P4J#8]
I'm trying to install P4J using python3.11 but got an error (I've attached the file in output from the command `python3.11 -m pip install P4J --log piplog.txt`). Instead, installation using python3.10 was successful. Could you help me fixing the issue?
[piplog.txt](https://github.com/phuijse/P4J/files/14370558/piplog.txt)

**Comment by phuijse** [comment]
Dear Francesco

The package has been updated to support the latest version of cython. You should be able to install for python 3.11 with no issues now. Please confirm

**Comment by fcotizelati** [comment]
Hello, 

I confirm that I could successfully install the package using python 3.11. Thank you!
